[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
dockerContext = "backend"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "./main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

